[general]
import = ["/home/daniel/.config/alacritty/themes/themes/citylights.toml"]

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 9
offset = { y = -2 }

[font.normal]
family = "GeistMono NF"

[window]
dynamic_title = false
opacity = 0.90
