import = ["/home/daniel/.config/alacritty/themes/themes/citylights.toml"]

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 9.5
offset = { y = -1 }

[font.normal]
family = "FantasqueSansM Nerd Font Mono"

[window]
dynamic_title = false
opacity = 0.95
