# vi: set ft=hyprlang :

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_center = true
    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    position = 0, -20
    halign = center
    valign = center
}
