[[mgr.prepend_keymap]]
on  = "y"
run = [ 'shell -- for path in "$@"; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

[[mgr.prepend_keymap]]
on  = "!"
run = [ "shell -- notify-send \"$(md5sum $1 | awk '{print $1}')\"" ]
desc = "Calculate MD5 checksum of selected file"
